//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_oauthtoken
    {
        public int authtoken_id { get; set; }
        public string sender_id { get; set; }
        public string outh_name { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
